services:
  backend:
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./server:/app
      - ./server/requirements.txt:/app/requirements.txt
    environment:
      PYTHONUNBUFFERED: "1"

  frontend:
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json