services:
  app:
    image: ghcr.io/vanserokok-arch/keis_crm_pro_ai-backend:latest
    pull_policy: always
    env_file:
      - ./server/.env           # переменные окружения для бэка
    environment:
      - PUBLIC_API_BASE=/api    # базовый URL API, под который собран фронт
    ports:
      - "8000:8000"             # внешний порт -> внутренний 8000
    restart: unless-stopped