# .github/workflows/build-docker.yml
name: Build Docker
on:
  workflow_dispatch: {}   # только вручную из вкладки Actions

jobs:
  frontend:
    uses: ./.github/workflows/frontend-ci.yml

  backend:
    uses: ./.github/workflows/backend-ci.yml